### ISSUE TITLE
Options are not logged to console

### ISSUE THREAD

**Issue by anselmbradford** [madlandproject/gulp-modernizr-build#5]
if running, for example, `modernizr( 'modernizr.min.js', { options: [ 'setClasses', 'html5printshiv' ] })`

The output in the console says

`Building Modernizr with these additional options :`

But doesn't list the html5printshiv option as being added, since only [specific options are logged](https://github.com/madlandproject/gulp-modernizr-build/blob/master/src/index.js#L179).

However, adding `console.log(modernirzConfig);` [here](https://github.com/madlandproject/gulp-modernizr-build/blob/master/src/index.js#L184) does show that config option is added.

**Comment by madlandproject** [comment]
Added in v0.0.6 296ecae
