### ISSUE TITLE
Remove deprecated gulp-util

### ISSUE THREAD

**Issue by mrcgrtz** [madlandproject/gulp-modernizr-build#6]
`gulp-util` is deprecated. Please replace it by following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Basically it’s this:

* `gutil.log` ➡️ https://www.npmjs.com/package/fancy-log
* `gutil.colors` ➡️ https://www.npmjs.com/package/ansi-colors
* `gutil.File` ➡️ https://www.npmjs.com/package/vinyl

**Comment by madlandproject** [comment]
Changed in v0.0.6 (296ecae)
